# Generated by Django 3.1.4 on 2021-03-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blognation', '0003_auto_20210310_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='cloth',
            field=models.CharField(choices=[('1', '100% Cotton'), ('2', 'Polycotton'), ('3', 'Polyviscos'), ('4', '100% Polycotton')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
