# Generated by Django 3.1.4 on 2021-03-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blognation', '0004_auto_20210325_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10000000000000000)),
                ('review', models.CharField(max_length=1000000000000000)),
            ],
        ),
    ]
