# Generated by Django 3.1.4 on 2021-03-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blognation', '0006_auto_20210328_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
