# Generated by Django 3.1.4 on 2021-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blognation', '0007_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=10000000000000000)),
                ('review', models.CharField(max_length=1000000000000000)),
            ],
        ),
    ]
